name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - run: cargo build --release

      - uses: actions/upload-artifact@v4
        with:
          name: kiosk
          path: target/release/kiosk.exe
